### ISSUE TITLE
KeyError: 'search_dn'

### ISSUE THREAD

**Issue by toddocon** [github/saml-ldap-team-sync#13]
search_dn is being parsed by class ADSync but search_dn is not shown in the example settings.yml. What should be the value of search_dn or is this a typo?

```
Traceback (most recent call last):
  File "SAMLTeamSyncAD.py", line 269, in <module>
    main()
  File "SAMLTeamSyncAD.py", line 170, in main
    adsync = ADSync(settings_file)
  File "SAMLTeamSyncAD.py", line 28, in __init__
    self.AD_SEARCH_DN = settings['ldap']['search_dn']
KeyError: 'search_dn'
```

**Comment by primetheus** [comment]
@toddocon thanks for opening up this bug! It seems as though you might be using an older version of the script... the new version, supporting pagination for thousands of entries, was merged in #7 and does not have that field. Can check with the new code to see if it still gives you issues? #12 has a branch with some bug fixes you might try
