### ISSUE TITLE
Searching LDAP by dn not working

### ISSUE THREAD

**Issue by sradi** [github/saml-ldap-team-sync#14]
Hi,

I played around with this sync tool and got this error:
`Traceback (most recent call last):
  File "SAMLTeamSyncAD.py", line 198, in <module>
    main()
  File "SAMLTeamSyncAD.py", line 108, in main
    group_members = adsync.get_group_members(args.ad_group)
  File "SAMLTeamSyncAD.py", line 54, in get_group_members
    member_list.append(self.get_attr_by_dn(member))
  File "SAMLTeamSyncAD.py", line 66, in get_attr_by_dn
    attributes=['sAMAccountName'])
  File "/home/s221676/.local/lib/python3.6/site-packages/ldap3/core/connection.py", line 786, in search
    check_names=self.check_names)
  File "/home/s221676/.local/lib/python3.6/site-packages/ldap3/operation/search.py", line 372, in search_operation
    request['filter'] = compile_filter(parse_filter(search_filter, schema, auto_escape, auto_encode, validator, check_names).elements[0])  # parse the searchFilter string and compile it starting from the root node
  File "/home/s221676/.local/lib/python3.6/site-packages/ldap3/operation/search.py", line 215, in parse_filter
    raise LDAPInvalidFilterError('malformed filter')
ldap3.core.exceptions.LDAPInvalidFilterError: malformed filter
`

I am wondering, how this search query ever worked:
https://github.com/github/saml-ldap-team-sync/blob/master/SAMLTeamSyncAD.py#L65

I was using
`user_filter2: (&(objectClass=USER)(dn={userdn}))`
where {userdn} is replaced by e. g. 'CN=John Smith,OU=__,,OU=__,OU=__,DC=example,DC=com'
I have ldap3 2.6.1 installed

According to this issue in ldap3 (https://github.com/cannatag/ldap3/issues/187), searching by 'dn' only works, if 'dn' is used as the search base, not as a search filter.
The python script works fine, after I changed it according to the suggestion in that issue.

Can anyone explain, if there is a way to use the script correctly in its current implementation or would you like me to open a pull request with my fix?

Best regards
Stefan

**Comment by primetheus** [comment]
Thanks for opening this up @sradi! I'm looking into this now... seems the filter initially should have been `distinguishedName` instead of `dn`, but in my testing I'm getting an empty result. I'll dig into it a bit more tonight

**Comment by primetheus** [comment]
@sradi this should be fixed by #17
