### ISSUE TITLE
"Circuit Breaker" threshold 

### ISSUE THREAD

**Issue by timhirsh** [github/saml-ldap-team-sync#23]
In similar spirit to https://github.com/github/saml-ldap-team-sync/issues/6, having some safety precautions around adding/removing large groups of individuals would be very valuable for larger organizations.  

For example, after initially syncing a team then setting up this tool to run every 15min in order to continuously sync incremental changes to memberships, I wouldn't expect more than 100 people to ever be added or removed in a single execution.  If so, it's probably a mistake and I'd prefer an exception to be thrown so a human can investigate why such a large change in membership is occurring before it actually occurs.

A possible solution that comes to mind is a "circuit breaker" or some kind of configurable threshold that can be set to say "never add/remove any more than N members at a time".

**Comment by primetheus** [comment]
@timhirsh this is implemented in the new version of the script, which is now a GitHub App. We'll do some additional testing, but the code is available in #33 if you'd like to test it out yourself
