### ISSUE TITLE
Add support for a mapping file

### ISSUE THREAD

**Issue by primetheus** [github/saml-ldap-team-sync#3]
At present, this script requires each team and group to be sync'ed separately. This means creating a wrapper to run `python SAMLTeamSyncAD.py -g <ad_group> -t <gh_team> -o <gh_org> -s` repeatedly to sync multiple teams. You can accomplish this with a wrapper script, but it would be ideal if this script could handle the mapping of multiples at once, fed via YAML

**Comment by primetheus** [comment]
short-term fix for this could be to wrap the script...


```python
#!/usr/bin/env python

script_dir = os.path.dirname(os.path.realpath(__file__))
settings_file = "{}/settings.ini".format(script_dir)
DATAFILE = "mapping.csv"

# Format the mapping file like this 
#<org>,<team>,<ldap-group>

try:
    with open(DATAFILE) as datafile:
        for line in datafile:
            [ org, team, group ] = line.split(",")
	    try:
		syncstr = "--sync --org {} --team {} --group {}".format(org, team, group) 
	        print("Syncing ORG: {}, TEAM: {}, LDAP_GROUP: {}".format(org, team, group)
	        os.system("{}/SAMLTeamSyncAD.py {}".format(script_dir, syncstr))
            except:
	        raise
except:
    raise
    
print "Sync completed!!"
```

**Comment by kumar0608** [comment]
@primetheus 
Thanks for the wrapper script, but it is little bit pain to maintain the csv files every time, 
In real-time GHE-Team and Ldap groups should be the same name always

If we are using GitHub enterprise service account user(API token) which will have access to all the organizations, so, in this case, get the teams from each org and search that team in  LDAP, if we found the GHE-Team in LDAP groups then we have to sync, if not then leave it and continue to the next team, it should be done for all ORGS.

Thanks
Pragnya

**Comment by primetheus** [comment]
@kumar0608 thanks for this context! So, if I’m understanding this correctly, the functionality you’d like to see is:

1. Look up teams in GitHub
2. Iterate over each team
3. Look up a team in LDAP that matches the name exactly
4. Sync the LDAP team to GitHub
5. Skip teams that aren’t found in LDAP

Is that accurate? I think that is pretty feasible and should be simple to implement. Then the additional flags can serve as overrides or additions.

**Comment by kumar0608** [comment]
yes exactly.

**Comment by primetheus** [comment]
@kumar0608 #33 is ready for testing, if you'd like to try it out. The README of that branch has been updated with instructions

**Comment by kumar0608** [comment]
Hi Jared

I got little confused with usage

Could you please help me

**Comment by kumar0608** [comment]
Hi Jarad,
i need some help on the version2, few questions regarding readme file and
usage

Thanks
Sridhar

**Comment by kumar0608** [comment]
Hi Jarad,

am getting initial setup errors,

/usr/local/bin/python3
/Users/sravula/Downloads/saml-ldap-team-sync-2.0/app.py
Traceback (most recent call last):
  File "/Users/sravula/Downloads/saml-ldap-team-sync-2.0/app.py", line 11,
in <module>
    from githubapp import GitHubApp, LDAPClient, CRON_INTERVAL, TEST_MODE
  File
"/Users/sravula/Downloads/saml-ldap-team-sync-2.0/githubapp/__init__.py",
line 26, in <module>
    OPEN_ISSUE_ON_FAILURE =
strtobool(os.environ.get('OPEN_ISSUE_ON_FAILURE', False))
  File
"/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/util.py",
line 301, in strtobool
    val = val.lower()
AttributeError: 'bool' object has no attribute 'lower'

Process finished with exit code 1

can you guide me
